baseURL = 'https://www.girtonball.com/'
languageCode = 'en-us'
title = 'GSB 2022'

disableKinds = ["taxonomy", "term"]

[params]
    description = "Welcome to the absurd world of the Girton Spring Ball! We are so excited to welcome you on Friday 18th March 2022! A link to the ticketing platform can be found here as well as all the information you need for the night. Our vision for the 2022 ball is to revive and celebrate the Girton community after a challenging two years, by way of a fun and responsible full-scale party. The theme of Absurdism perfectly reflects both the strangeness of recent collective experience whilst also celebrating the creativity and light-heartedness of our long history of Spring Balls. As Camus said “The realisation that life is absurd cannot be an end, but only a beginning…”. We mean to start as we mean to go on."